### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by therahulkumar** [fizyr/keras-retinanet#1021]
Is there any plan of releasing docker image.

**Comment by de-vri-es** [comment]
No, it should run fine on any environment with recent enough python and dependencies.

**Comment by therahulkumar** [comment]
Often we need to create a docker image for running the model as containerised application especially if you want to run it in production system. I am working on a similar problem, I can create a PR if you think it is good to have.

**Comment by de-vri-es** [comment]
Personally I'm not in favour of adding Docker images or Docker build files for a couple of reasons:

* Adding Docker images based on some platform would somehow indicate that that is the preferred platform for using `keras-retinanet`. However, there is no preferred platform. Any platform with the right dependencies should work.

* If `keras-retinanet` breaks on some specific platform due to portability issues, we would actually want to fix those. Adding Docker into the mix has the risk of significantly reducing the number of distinct platforms people use `keras-retinanet` on.

* If I recall correctly, using Docker with nvida/cuda requires some special version of Docker or some specific configuration. Otherwise their could be issues when the nvidia driver of the Docker image isn't the same as the nvidia driver of the host machine. I'm not sure what the exact story is, but I also don't really want to find out.

* At Fizyr, nobody would be using the Docker images, meaning they won't really be maintained. While they should keep working (they are Docker images after all), they also wouldn't receive regular updates, which means they may lag behind in performance.

* There's quite some issues posted here by people who simply misconfigured their system. You could predict that using Docker would reduce the number of issues. However, I deeply suspect it would only shift the subject of the issues to installing/configuring/using Docker instead of installing/configuring/using Python and Keras.

* I'm not even sure the scripts in this repository make sense to use in production. They're only simple command line tools. I imagine most serious applications will want to integrate `keras-retinanet` differently, either directly calling Python code or by adding some client/server application around it. In that case, it's not so strange for the writer of that application to create their own Docker image.

These are my feelings though. Maybe others feel differently?

**Comment by therahulkumar** [comment]
Valid reasons @de-vri-es, maintenance is going to be a big issue and updating the docker image every time you change anything would be an overhead.
