### ISSUE TITLE
map

### ISSUE THREAD

**Issue by zhangyufei1995** [fizyr/keras-retinanet#1086]
During the training process, map began to increase, but it remained unchanged at 0.9969 after 40 epoch. What is the reason?

**Comment by hgaiser** [comment]
What do you mean? Why do you think it should change?

**Comment by zhangyufei1995** [comment]
Isn't it a slight change?Always 0.9969 after epoch40

**Comment by hgaiser** [comment]
Doesn't have to be; the mAP is a summary for how many objects have been detected. Imagine a network that almost perfectly detects all your objects, the mAP score will be 1 since all objects are properly detected. The next epoch, the boxes will be slightly different, but still nearly perfect. The mAP will still be 1 then, since they are still all properly detected.

**Comment by zhangyufei1995** [comment]
Appreciate
