### ISSUE TITLE
how to use  tensorrt to speed up  inference ?

### ISSUE THREAD

**Issue by CHONGCHUANSHENG** [fizyr/keras-retinanet#1094]
i want to use the tensorrt to speed up the inference net , i have changed the  h5 model to pb  type. but i don't know how to  use the tensorrt , the offical web of tensorrt didn't provide the retiananet demo that can use. anyone  know it?

**Comment by ruyijidan** [comment]
you can try refer this repo
https://github.com/ardianumam/Tensorflow-TensorRT

**Comment by CHONGCHUANSHENG** [comment]
okay     i have  a try     thank u  very much！



------------------ 原始邮件 ------------------
发件人: "ruyijidan"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 下午3:44
收件人: "fizyr/keras-retinanet"<keras-retinanet@noreply.github.com>; 
抄送: "2019 up up up"<282028340@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [fizyr/keras-retinanet] how to use  tensorrt to speed up inference ? (#1094)




you can try refer this repo
 https://github.com/ardianumam/Tensorflow-TensorRT

**Comment by hgaiser** [comment]
We don't officially support TensorRT. I believe, from seeing other conversations, you'll need to port the custom layers from keras-retinanet to TensorRT for it to work.

That said, since there isn't an issue here, I'm closing this.

**Comment by bfialkoff** [comment]
@CHONGCHUANSHENG any success I'm working on the same thing?

**Comment by anuar12** [comment]
@bfialkoff Any success for you? Perhaps it would be very simple using TF-TRT in TF1.14.

**Comment by ccsone** [comment]
@bfialkoff    without success。 now  i try to analysis the keras model    and transform into caffemodel

**Comment by ccsone** [comment]
@anuar12  you use TF-TRT  that  it can success?

**Comment by anuar12** [comment]
I will try by the end of next week, let you know if it worked.

**Comment by Egorundel** [comment]
Who managed to convert the model into TensorRT?

I converted model.h5 to **SavedModel**, then to **ONNX**, and then I can't convert to **TensorRT engine**.

Model structure after training:
![Screenshot from 2023-10-11 10-20-00](https://github.com/fizyr/keras-retinanet/assets/65890558/aae5df59-c870-47e3-9857-1f2c3e9b8e85)

Error when converting from ONNX to TensorRT engine:
![Screenshot from 2023-10-11 10-20-57](https://github.com/fizyr/keras-retinanet/assets/65890558/37f6462c-a915-47e1-9313-2d9d4964385f)

**Comment by Egorundel** [comment]
@hgaiser @anuar12 @CHONGCHUANSHENG @bfialkoff @ruyijidan @ccsone Hello, could you help, please?

**Comment by hgaiser** [comment]
Afraid I can't, I have no experience with TensorRT.

**Comment by Egorundel** [comment]
@hgaiser Hello, what if I want to make the dimensions of the input image not [None, None, None, 3], but I want to make [None, 512, 512, 3]? And so that all other layers depend on these sizes?

I have already changed in **resnet.py** line `inputs = keras.layers.Input(shape=(None, None, 3))` 
on line `inputs = keras.layers.Input(shape=(512, 512, 3))`
![resnet.py](https://github.com/fizyr/keras-retinanet/assets/65890558/4c0c619b-0260-415c-af2b-8c5c2dc4fe40)

And at the start of training, when calling `model.summary()`, you can understand that changes have occurred:
![start training](https://github.com/fizyr/keras-retinanet/assets/65890558/b59ef6fa-6e97-4c97-a178-9c8365145f98)

But the training does not start, because the following error occurs:
![2023_10_13_0jt_Kleki](https://github.com/fizyr/keras-retinanet/assets/65890558/75599208-ba70-4469-a20b-5e5edde03413)

The problem with the optimizer...
What else needs to be changed so that the training data generator produces images in a batch with a resolution of 512x512. Can you help, please?
