### ISSUE TITLE
Transfer learning problem in training retinaNet with resnet50 backbone

### ISSUE THREAD

**Issue by thaisacorreia** [fizyr/keras-retinanet#1101]
Hello,

I am trying to train retinaNet with the restnet50 backbone and my own CSV data, using as input the pre-trained model provided by you: "--weights snapshots / resnet50_coco_best_v2.1.0.h5".

However in training the following error is indicated: "UserWarning: Skipping loading of weights for layer classification_submodel due to mismatch in shape ((3, 3, 256, 630) vs (720, 256, 3, 3))"

I would like to know if in this case the training is started without any initial weight? And if this happens how can I get around this problem, and then I can introduce the weights into the training using my own base with a different number of classes.

Thank you very much in advance.

**Comment by hgaiser** [comment]
The line you copied is not an error, but a warning, letting you know that the weights of "classification_submodel" we're not copied to the new network. The reason is that your new network has a different number of classes to classify then your old network, so the sizes of the weights don't match up. This is fine and expected and there is no harm in ignoring this warning.

**Comment by thaisacorreia** [comment]
Thank you for your answer.

I changed classes amount and the warning not showing, transferring weights properly.
