### ISSUE TITLE
Error Incompatible shapes evaluation.py

### ISSUE THREAD

**Issue by vgilabert94** [fizyr/keras-retinanet#1107]
Hi everyone, i have got an error when i was evaluating my model.

Im using Google Colab for run the model. I have google colab sync with my google drive where i have the dataset and the model folders.(https://colab.research.google.com/drive/1OJFH5Pf5bKm2tBovzeeoTrtoEYIEK-Dq)

I train the model 10 epochs with config.ini file, because i have an optimized anchors. After train, i convert the model, using --config. But when i want to evaluate the model converted obtain the results mAP, I got this error (you can see the complet error in the google colab file):

tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [1,177678] vs. [1,493550]
	 [[{{node boxes/mul_7}}]]
	 [[filtered_detections/map/while/GatherNd_2/_1879]]
  (1) Invalid argument: Incompatible shapes: [1,177678] vs. [1,493550]
	 [[{{node boxes/mul_7}}]]
0 successful operations.
0 derived errors ignored.

I don't know what is the problem. How I can solve this? Any ideas?

**Comment by MuhammadIrfanAli** [comment]
Just to let other know, the problem was solved by setting bs to 1 (details on slack channel)

For me, the above problem got solved by appending `.ini` to config parameters file. I was not passing the extension name during training and I was passing the extension name while converting the model for inference. Since my anchor_parameters were not default, it caused the error. Hope it help others.

**Comment by vcarpani** [comment]
OK, closing this issue then ;)
