### ISSUE TITLE
testing code for custom dataset?

### ISSUE THREAD

**Issue by HuangBo-Terraloupe** [fizyr/keras-retinanet#113]
Hello everyone,
I have 2 questions.
1, Do we have a test code for custom dataset, or what should we modify based on the testing notebook of COCO dataset?

2, I am doing the object detection on a wild range. So far I only use the image patches that contains at least one object for training. So the model works not good for the images, which is totally background. How can I add these negative samples into my training set? 
(Can I simply add these images into training set and write corresponding csv as empty?

**Comment by HuangBo-Terraloupe** [comment]
1, Thanks for the quick answer, I will give try based on the COCO testing code.
2, @yhenon  For the second question, can we do this in your faster rcnn repo?  I think faster rcnn will take the Region Proposal, which intersects with any groundtruth bounding box less than 30% as negative samples. But how should we do for the images, which are totally background. 
Thanks in advance!

**Comment by hgaiser** [comment]
Having an image with no annotations is possible and supported by the training process. However the CSV generator lacks support for adding images with no annotations.

One solution would be to add a line in your CSV with one annotation with a bounding box of `(0, 0, 1, 1)`. Since it won't significantly intersect with any anchor it will not affect your training, but it would mean your image is included in the dataset.

**Comment by HuangBo-Terraloupe** [comment]
cool!
If I doing this, the model will sample negative samples from these images?
I will try to put these images into training set, and make its corresponding annotation like:
/data/imgs/img_001.jpg, 0, 0, 1, 1, 'bg' 
And give a try.

**Comment by hgaiser** [comment]
Yeah that should happen. The class `bg` should exist though. If it doesn't exist, just use any class that does exist, it will ignore that annotation anyway.

I will close this issue since it seems resolved.
