### ISSUE TITLE
Relative image paths in CSVGenerator

### ISSUE THREAD

**Issue by de-vri-es** [fizyr/keras-retinanet#117]
Relative image paths in the CSV generator are resolved with respect to the current working directory.

However, in the interest of having relocatable datasets, it might make sense to resolve them with respect to the directory of the CSV file.

@hgaiser , @yhenon , what do you guys think?

**Comment by hgaiser** [comment]
The COCO and Pascal generators work slightly different. They expect a working directory and the name of a file listing which images to use. Of course there you can expect the (for COCO for instance) the annotations to be in the `annotations` folder since that's how the COCO dataset looks like. But perhaps the CSV generator could do something similar by looking for the annotations / images / class file relative to the given working directory?

**Comment by de-vri-es** [comment]
I would prefer not to hardcode the names of the csv files, if that is what you propose. That would reduce the flexibility of the generator. The pascal and VOC generator aren't flexible at all, but the CSV generator is.

Without reducing flexibility we could have three parameters:
* annotations file
* class file
* base directory

Then if directory isn't given it could be deduced from the annotations file, and if directory is given we can deduce a default for annotations file and class file. That does get a bit more complicated to explain though.

Simply having relative paths in a file be relative to the directory of that file is quite a bit easier to explain, although less flexible.

**Comment by de-vri-es** [comment]
Initial implementation at the [csv-relative-paths](https://github.com/fizyr/keras-retinanet/tree/csv-relative-paths) branch. It should be relatively straight-forward to expose the `base_dir` argument to users.

**Comment by de-vri-es** [comment]
Indeed :)

**Comment by de-vri-es** [comment]
Closing this in favour of #125
