### ISSUE TITLE
Input shape and output values

### ISSUE THREAD

**Issue by kawshik8** [fizyr/keras-retinanet#128]
What is the shape of the input image shape for the model trained using train_csv.py?
If my image is (rows,columns,channels) how does the model expect the input?

What is the output from the model?
What does detections denote?
What does each dimension in detections denote?
How do I extract bounding boxes (x1,x2,y1,y2) from detections?

**Comment by hgaiser** [comment]
If you didn't change the `image_min_side`/`image_max_side` arguments for the generators, it is trained on images who's smallest side equals 600 pixels. Other sized images can be run through the network as well though, there aren't really constraints on the size (except for GPU memory limits and a lower limit of I believe 224x224).

Regarding the output, these questions are answered in the README.md.

I will close this issue since it's not really an issue. If you like to discuss further, I advise to join the `#keras-retinanet` channel on the keras slack team.
