### ISSUE TITLE
AttributeError: 'int' object has no attribute 'split'

### ISSUE THREAD

**Issue by anizeani** [fizyr/keras-retinanet#1485]
In the def: 
setup_gpu(gpu_id) 
I get an error 'int' object has no attribute 'split' 

when calling setup_gpu(0)

~/.local/lib/python3.7/site-packages/keras_retinanet/utils/gpu.py in setup_gpu(gpu_id)
     20 def setup_gpu(gpu_id):
     21     try:
---> 22         visible_gpu_indices = [int(id) for id in gpu_id.split(',')]

the code in jupyter:
#automatically reload modules when they have changed
%matplotlib inline

%load_ext autoreload
%autoreload 2

#import keras
from tensorflow import keras

#import keras_retinanet
from keras_retinanet import models
from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image
from keras_retinanet.utils.visualization import draw_box, draw_caption
from keras_retinanet.utils.colors import label_color
from keras_retinanet.utils.gpu import setup_gpu

#import miscellaneous modules
import matplotlib.pyplot as plt
import cv2
import os
import numpy as np
import time

#use this to change which GPU to use
gpu = 0

#set the modified tf session as backend in keras
setup_gpu(gpu)

**Comment by rcastberg** [comment]
I found a workaround by setting 
`gpu = "0,"`

**Comment by Syed05** [comment]
I am facing same issue, anyone find solution?

**Comment by enliden1** [comment]
I am also facing same issue...

**Comment by mahesaAtma** [comment]
in my case, because i'm not using the GPU, i comment the line

where the file is in
examples/keras50_retinanet.py

**Comment by richeym-umich** [comment]
We also had this issue, it seems to have been introduced when the compatibility code for tf2 was removed (commit 7ef975f). We fixed by reverting to the compatibility code, but it can also be fixed by adding an except statement to catch the Attribute Error:
`except (ValueError, AttributeError) as e:
tf.config.set_visible_devices([], 'GPU')
`
Another fix, as noted above, is to set your gpu input to a list:
`gpu="0,"`
