### ISSUE TITLE
Got the error using a custom dataset: ValueError: invalid CSV annotations file: instances_test2019.csv: line 1: malformed x1: invalid literal for int() with base 10: 'x1' 

### ISSUE THREAD

**Issue by jq28** [fizyr/keras-retinanet#1495]
I converted the values to ints but still to no avail

**Comment by LexisDG** [comment]
Hello, @jq28 I was wondering how you fixed the error. I have the same error and dont really know how to fix it since 'x1' is the header of the df. Heres an example of my .csv file :

location , x1, y1, x2, y2, class_name
00075dcb146266ff.jpg, 117, 316, 215, 477, Mug

Note that the added spaces are for readability :)

**Comment by LexisDG** [comment]
Still not sure why Keras is doing this, but I ended up not saving the header in the .csv file like so :

df.to_csv('file.csv', index=False,header = False) #Fix for line 1: malformed x1: invalid literal for int() with base 10: 'x1'

And I dont have this issue now :D
