### ISSUE TITLE
Do you have any special reasons for using cv2.resize? 

### ISSUE THREAD

**Issue by Ting-Crush** [fizyr/keras-retinanet#1501]
Why resize using cv2.resize instead of using PIL.Image.resize?
The reason I thought like this is because I used PIL.Image to read images, so I thought I should do PIL.Image.resize for consistency.

Do you have any special reasons for using cv2.resize?
(e.g., performance issues)

![image](https://user-images.githubusercontent.com/40261179/104158872-98e1d600-5431-11eb-91d1-48699b5e1462.png)

**Comment by hgaiser** [comment]
I believe indeed cv2 was used because it was more efficient compared to PIL. For image reading cv2 was also a bit more efficient, but PIL offered clearer errors (like "FileNotFoundError: file ... does not exist" kinda errors). cv2 would just return None in case of errors, without saying anything about the cause.
