### ISSUE TITLE
How do I calculate accuracy after training?

### ISSUE THREAD

**Issue by dev2y** [fizyr/keras-retinanet#1519]
I ran evaluate.py script with my converted model and test data and got the following output.

Is precision is my accuracy? Is it 9% or 97%. I am asking because recognition after training is pretty good.

```
Running network: 100% (16 of 16) |###################| Elapsed Time: 0:00:13 Time:  0:00:13
Parsing annotations: 100% (16 of 16) |#################| Elapsed Time: 0:00:00 Time:  0:00:00
2225 instances of class cell with average precision: 0.0970
Inference time for 16 images: 0.8011
mAP using the weighted average of precisions among classes: 0.0970
mAP: 0.097

```

**Comment by hlmhlr** [comment]
> I ran evaluate.py script with my converted model and test data and got the following output.
> 
> Is precision is my accuracy? Is it 9% or 97%. I am asking because recognition after training is pretty good.
> 
> ```
> Running network: 100% (16 of 16) |###################| Elapsed Time: 0:00:13 Time:  0:00:13
> Parsing annotations: 100% (16 of 16) |#################| Elapsed Time: 0:00:00 Time:  0:00:00
> 2225 instances of class cell with average precision: 0.0970
> Inference time for 16 images: 0.8011
> mAP using the weighted average of precisions among classes: 0.0970
> mAP: 0.097
> ```

Dear @dev2y , precision and accuracy both are different. Precision gives you information about percentage of true positive predictions among total posotives predicted while accuracy is calculated for overall predictions including both positive and negative predictions. 
Here in this evaluation function, precision is being calculated and by 0.097 it means 9.7%. You should try with some other test  images as well for the sake of your own clarification.

**Comment by dev2y** [comment]
Thanks a lot @hlmhlr 

Working on annotations. Is there a script or a command to calculate accuracy for keras-retinanet?

**Comment by hlmhlr** [comment]
> Thanks a lot @hlmhlr
> 
> Working on annotations. Is there a script or a command to calculate accuracy for keras-retinanet?

Dear @dev2y , in the keras-retinanet you can only find out average precision by running the code evaluate.py 

Also in multi class object detection, accuracy is not calculated. It is not a suitable metric to evaluate the performance of multi class object detector.  Few reasons could be:  in accuracy calculation you need all predictions TP,TN, FP and  FN but in object detection scenario we do not consider TN predictions because during detection thousands of empty boxes are generated. And the formula of accuracy involves TP+TN/TP+FN+FP+TN,  and we don't use TN, So no accuracy measurements. 
If you have imbalanced dataset for your multi classes, then calculating accuracy would not reflect the performance of individual class rather you will get overall accuracy of the system and that could be misleading. 

I would suggest you to have some readings regarding evaluating metrics of object detection and decide which metrics you need to use based upon your problem type.
