### ISSUE TITLE
How to change anchor size?

### ISSUE THREAD

**Issue by Kongsea** [fizyr/keras-retinanet#154]
Since the sizes of my input images are smaller than the original COCO or PASCAL pictures, I want to change the anchor size accordingly to make my model better.
Then my objects to be detected are of a nearly fixed size and the ratio between width and height is almost fixed. So I want to change the ratios and scales too.
But after I change it, for example, change `sizes=[16, 32, 64, 128, 256], strides=[4, 8, 16, 32, 64]` to `sizes=[32, 64, 128, 256, 512], strides=[8, 16, 32, 64, 128]`, the detections are scaled down to localized in a corner, so I think I have make a mistake.
So could anyone give me some help to tell me, How can I modify this parameters to change the anchor size.
Thank you.

**Comment by Kongsea** [comment]
If the objects to be detected are slim long ones, How should I change `ratios=np.array([0.5, 1, 2], keras.backend.floatx()), scales=np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx())`?
Should I change `ratios` to [0.4, 0.7, 1.0]? Then how about `scales`?

**Comment by hgaiser** [comment]
I think you should try to visualize the anchors you're generating on one of your images. Try using `keras_retinanet.utils.anchors.anchors_for_shape` to generate all anchors and visualize a couple of them. Visualizing them will help you get a feel of what those values do and mean.

Other than that, my advice is to only adjust `scales` and `ratios`, since the other parameters (`sizes` and `strides`) are influenced by network architecture. You also have to make sure that the [`Anchors` layer](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/layers/_misc.py#L25) is using the same parameters. There isn't a nice solution in `keras-retinanet` to pass along these values, so you'll have to figure out some "hacky" way to adjust them in that layer.

**Comment by Kongsea** [comment]
Thank you for your quick answer and kind advice. I will have a try and investigate it.

**Comment by hgaiser** [comment]
Can I consider this issue resolved? We should maybe have further discussions on Slack (check readme for how to connect).

**Comment by Kongsea** [comment]
OK, I will close it now. Thank you.
