### ISSUE TITLE
Performance of resnet101_retinanet

### ISSUE THREAD

**Issue by ksw9446** [fizyr/keras-retinanet#221]
I trained RetinaNet based ResNet-50 and ResNet-101 from code.
training data is VOC2007 trainval, and test data is VOC2007 test.
After training model, I evaluate models' mAP using 'eval.py'.
ResNet-50 base's result : 60.6
ResNet-101 base's result : 59.3

Are these performance normal rate?
I want to know why resnet-101 base's mAP is evaluated lower than resnet-50 base.
thank you.

**Comment by giladdiv** [comment]
@hgaiser 
The original faster-rcnn paper is based on VGG, does resnet gives better results?
Do you by any chance know what are the state of the art results for faster rcnn on VOC2012?

**Comment by ksw9446** [comment]
@hgaiser 
Thank for answering.
I used keras-retinanet/keras_retinanet/utils/eval.py in evaluate branch
Is it wrong method?

**Comment by hgaiser** [comment]
Ah I see I didn't know you were using that branch. It's under development so it might not work correctly yet, bear that in mind.

@giladdiv I think you can find a comparison in the ResNet papers, otherwise I'm sure there are other places where this is documented. From what I recall, ResNet outperforms VGG16 on VOC and COCO.

**Comment by ksw9446** [comment]
Thanks for your answer. :)

**Comment by hgaiser** [comment]
I'll go ahead and close this since there is nothing left to do. For further discussions on this I'd invite you to the Slack channel.
