### ISSUE TITLE
How can I train with other model

### ISSUE THREAD

**Issue by cuongnc220592** [fizyr/keras-retinanet#233]
I want to use retinanet with another models eg VGG or own model.

**Comment by hgaiser** [comment]
Currently only ResNet is implemented, but the code is set up so that any backbone that follows a similar architecture (5 stages) can be used. If you follow the [ResNet example](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/resnet.py#L79), but replace the backbone with a VGG model that returns those 5 stages, then it should work.

For further discussions on this topic I advise you to join the Slack channel.
