### ISSUE TITLE
BBox do not appear

### ISSUE THREAD

**Issue by rbothra3** [fizyr/keras-retinanet#242]
Hi all,

I did the following to train my dataset:

1. Installed Retinanet
2. Created a csv with my data in the recommended format
3. Ran: retinanet-train csv /home/rohit/Downloads/data_csv4.csv /home/rohit/Downloads/catcsv.csv
4. The training ran for about 1.5 days, 50 echos and created 50 snapshots in the snapshots folder
5. Edited the example file to change the path to: 

`model_path = "/home/rohit/Downloads/keras-retinanet/snapshots-old/resnet50_csv_10.h5"
`
When I run the example file, I do not get a bounding box. I get one warning which states: 

```
/home/rohit/.local/lib/python3.6/site-packages/keras/models.py:255: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

```
Did I miss something? Again, thank you for your help!

**Comment by yhenon** [comment]
There was a significant bug(https://github.com/fizyr/keras-retinanet/pull/240) until recently that affected training. Could you check if the code you used was affected by the bug? If so, you'll have to retrain unfortunately (although it should take less than 1 day before you can check to see if you are starting to get predictions at low confidences).

**Comment by rbothra3** [comment]
I used the base from three days ago. Running it again to verify the performance.

**Comment by hoangminhtoan** [comment]
Dear,

I updated the #240 bug and re-run with pascal dataset. I still get the warning "No training configuration found in save file:". And one more thing, after I train with default configs (50 epochs, 10000 steps/ epoch, weights = 'resnet50') I did not get the good result as your example. It only detects a guy on the screen and recognizes him as a bird.

![screenshot from 2018-01-29 10-00-56](https://user-images.githubusercontent.com/1559257/35489573-a5463cea-04db-11e8-8002-c6da630cf353.png)

**Comment by hgaiser** [comment]
It's unfortunate, but it seems https://github.com/fizyr/keras-retinanet/pull/244 could have also been negatively affecting your results. Could you try retraining after that patch?

**Comment by hoangminhtoan** [comment]
Thanks, I am re-running with different weight ('imagenet' as default) to see the performance. It'll take me 1.5 days for training. then I'll update #244 and see.

**Comment by hgaiser** [comment]
@hoangminhtoan if your current training does not include #244 , but does include any form of data augmentation (even flips, which are enabled by default) then it is pointless to continue training as the result will be suboptimal. My advice is to restart the procedure on the latest `master` version.

**Comment by hoangminhtoan** [comment]
@hgaiser. thanks for your support, I pulled the newest version and have been running it since yesterday.

**Comment by hgaiser** [comment]
Alright, if it solved your issue, would you close this?

**Comment by rbothra3** [comment]
#244 Fixed the issues. Thanks!

**Comment by adavradou** [comment]
Hello everyone!

I face the same issue, no bounding box appears when evaluating the model. 

I trained the model the model for 20 epochs on Colab using a train.csv file. 
I converted the last snapshot to inference model and then trying to test on a test.csv. 

However, the mAP seems to be calculated.


`Loading model, this may take a second...
2022-01-19 14:24:30.713078: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
Running network: 100% (200 of 200) |######| Elapsed Time: 0:00:49 Time:  0:00:49
Parsing annotations: 100% (200 of 200) |##| Elapsed Time: 0:00:00 Time:  0:00:00
254 instances of class ulcer with average precision: 0.6791
Inference time for 200 images: 0.0907
mAP using the weighted average of precisions among classes: 0.6791
mAP: 0.6791`

Any ideas what could be the problem?
Thank you in advance.
