### ISSUE TITLE
Change Backbone

### ISSUE THREAD

**Issue by DennisMaier** [fizyr/keras-retinanet#274]
Hey, great work!

Is there an easy way to use another backbone such as vgg or a custom one instead of Resnet?
Where do I have to insert the model?

And for some reason I could not start a training from scratch (with no weigths). When I start the training with "None" for weights it says, it cant find the weights file =(

Any ideas what I'm doing wrong?

**Comment by de-vri-es** [comment]
Hey :)

You can use different backbone, although this is not exposed through the train script provided here. See also #233.

As for training without any initial weights, that is currently not possible through the `train.py` script due to an oversight on our part. I submitted a PR to fix that: #275. You can try it out if you want, but be aware that it hasn't really been tested yet.

**Comment by hgaiser** [comment]
Seems this question is answered? For further discussions on this topic, feel free to join the Slack channel.

**Comment by hgaiser** [comment]
Isn't adaboost intended for weak classifiers, such as with haar-like features? It feels out of place here.
