### ISSUE TITLE
How much data should I train to get good results?

### ISSUE THREAD

**Issue by milkplz** [fizyr/keras-retinanet#285]
Thank you for the great implementation.!!

I did train model (batch 1, echo 1, step 10000)
But Model was not working well.

How much data should I train to get good results?

**Comment by fastlater** [comment]
How much data (samples) are you using to train? How many classes or outputs do you expect?
In you can say, what are you trying to detect?

**Comment by hgaiser** [comment]
Finding the right amount of data highly depends on your problem area. For instance, detecting white squares on black images is a far simpler task than detecting faces in images. In general with "normal" object detection, we've seen sensible results with as low as 100 images.

If you have a specific problem, please open an issue for that. Otherwise I trust this answers your question.
