### ISSUE TITLE
how to annotate

### ISSUE THREAD

**Issue by anjuasadel** [fizyr/keras-retinanet#293]
can you please tell me which annotation tool you have used for annotating your own dataset. 
or how did u convert it in the format required for this model.

if possible please share the link for annotation tool or  the convert.py file for that.

Thank you.

**Comment by de-vri-es** [comment]
We don't have an annotation tool we can share.

You can choose from a number of different formats to feed the annotations into the train script. The easiest format is the CSV format. See the README for more details.

It should not be difficult to write code for exporting to that format. But since it depends on what you're using to do annotations, it doesn't make sense for us to provide anything along those lines.
