### ISSUE TITLE
How to train retinanet using my own xml files taken from Labelimg

### ISSUE THREAD

**Issue by barkntuncer** [fizyr/keras-retinanet#312]
Hello,

I would like to train retinanet with my own data. However, I have labeled my data with labelimg which gives me the necessary xml files. Do I have to convert these annotations to a csv file in order to use `csvgenerator.py` ?  Can I just use the xml files that I have ? 

Thanks in advance
Barkin

**Comment by mkocabas** [comment]
Hi, yes you have to convert the .xml file into the proper csv format explained in README to use it with csv generator.

On 4 Mar 2018, at 20:44, barkntuncer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I would like to train retinanet with my own data. However, I have labeled my data with labelimg which gives me the necessary xml files. Do I have to convert these annotations to a csv file in order to use csvgenerator.py ? Can I just use the xml files that I have ?

Thanks in advance
Barkin

**Comment by barkntuncer** [comment]
Alright thank you!

**Comment by barkntuncer** [comment]
Well, I could not figure out how to use the csv_generator.py in preprocessing file can you lead me ? Should i use the debug.py file ? 

Barkin

**Comment by andongchen** [comment]
HI,I have write a script to change xml data to csv:
import csv
import sys
import os
import xml.etree.ElementTree as ET

split = 'trainval'
img_path = '/devdata/chenandong/VOCdevkit2007-kitty/VOC2007/JPEGImages'
trainval_or_test_path = '/devdata/chenandong/VOCdevkit2007-kitty/VOC2007/ImageSets/Main/{}.txt'.format(split)
anno_path = '/devdata/chenandong/VOCdevkit2007-kitty/VOC2007/Annotations'
f_annotations = open('./data/kitti_annotations_{}.csv'.format(split), 'w', newline='')
f_clsses = open('./data/kitti_clsses_{}.csv'.format(split), 'w', newline='')
classes = ['Pedestrian','Car','Cyclist']

f_txt = None
if sys.version_info[0]<3:
    f_txt = open(trainval_or_test_path, 'rb').readlines()
else:
    f_txt = open(trainval_or_test_path, 'r').readlines()
csv_writer_anno = csv.writer(f_annotations, dialect='excel')
csv_writer_cls = csv.writer(f_clsses)
# csv_writer.writerow(list)

num = 0
for line in f_txt:
    num += 1
    print(num)
    line = line.strip()
    img_file = os.path.join(img_path, line+'.png')
    tree = ET.parse(os.path.join(anno_path,line+'.xml'))
    root = tree.getroot()

    for obj in root.iter('object'):
        cls = obj.find('name').text
        assert cls in classes, cls +'not in classes'
        csv_writer_cls.writerow([cls,str(classes.index(cls))])
        xmlbox = obj.find('bndbox')
        bbox = (float(xmlbox.find('xmin').text), float(xmlbox.find('ymin').text), float(xmlbox.find('xmax').text),
                float(xmlbox.find('ymax').text))
        l = [img_file, str(bbox[0]), str(bbox[1]), str(bbox[2]), str(bbox[3])]
        csv_writer_anno.writerow(l)

**Comment by mkocabas** [comment]
Hi @barkntuncer, you don't need `csv_generator.py` to start training. After preparing csv annotations properly as stated in README, you can run `python keras_retinanet/bin/train.py csv /path/to/csv/file/containing/annotations /path/to/csv/file/containing/classes` script. In addition to that `debug.py` provides a visualization tool for your annotations. It's better to visualize ypur annotations before starting a training. In order to do that it is enough to change `train.py` with `debug.py` in above script.

**Comment by hgaiser** [comment]
This question seems sufficiently answered.
