### ISSUE TITLE
How to change relative imports to absolute imports? 

### ISSUE THREAD

**Issue by smehida** [fizyr/keras-retinanet#320]
Hi,
I copy the new version of retinanet to another place, but it uses previous version configuration, in the debug.py it says change relative imports to absolute imports to solve the problem. How can I do that?

**Comment by tmontaigu** [comment]
Relative import : ` from ..preprocessing.pascal_voc import PascalVocGenerator`
Absolute import: ``` from keras-retinanet.preprocessing.pascal_voc import PascalVocGenerator```

**Comment by smehida** [comment]
I don't have keras-retinanet instead of that I have detection_net folder, should I use that name?

**Comment by tmontaigu** [comment]
If you renamed the keras-retinanet folder to detection_net then yes

**Comment by smehida** [comment]
I add from keras_retinanet_v2.keras_retinanet.models.mobilenet import custom_objects in the first line of my test program, but it throws me below error:
 ImportError: No module named keras_retinanet_v2.keras_retinanet.models.mobilenet

**Comment by tmontaigu** [comment]
Python's imports must match the underlying folder structure, also the keras_retinanet_v2 folder has to be visible to python, so it should be in the Python's path

**Comment by de-vri-es** [comment]
> I don't have keras-retinanet instead of that I have detection_net folder, should I use that name?

Why did you rename it? If you wish to write custom scripts or modules for integrating `keras-retinanet` with your own application, I would strongly recommend keeping `keras-retinanet` as it is and writing your own code as an external module that imports `keras_retinanet`.

Otherwise you will have a very very difficult job keeping up to date with changes from this repository.

Also, if you do wish to fork and rename the repository (you may of course), then support for that is out of scope of this issue tracker.

**Comment by hgaiser** [comment]
@smehida is your issue resolved? If so, please close it.
