### ISSUE TITLE
Training on customized dataset

### ISSUE THREAD

**Issue by Doodleshr** [fizyr/keras-retinanet#321]
Hi,

I am trying to train on my own dataset that has two types of object(lion and leopard) and there are several questions I hope you guys can help to clarify:

1.  judging by preprocessing/pascal_voc.py,  image width and height information are not used from corresponding XML? If so, how does it aquire these information?
2.  if I would like to narrow the classification problems down two category, is there anything else I need to modify besides voc_classes defined in pascal_voc.py?
3. I trained two models each with 50 epochs and neither of them is giving good estimations even on training sets, do you think hyper parameter tuning is helpful in this case?

Thanks for your time
shr

**Comment by hgaiser** [comment]
> You should not modify pascal_voc.py. I strongly recommend using the CSV format for you own datasets. See the README.md for more details.

There should indeed be no need to modify any of the generator code. If you wish to run on your Pascal dataset, the generator should expose all the necessary arguments you need. Although as @de-vri-es said, I'd advise to use the CSV generator for custom datasets.

> I trained two models each with 50 epochs and neither of them is giving good estimations even on training sets, do you think hyper parameter tuning is helpful in this case?

You could try running `keras_retinanet/bin/debug.py` on your dataset. If there are no results, 9/10 times it's because of the data.

**Comment by hgaiser** [comment]
@Doodleshr is your issue resolved? If so, please close it.
