### ISSUE TITLE
Method for configuration

### ISSUE THREAD

**Issue by hgaiser** [fizyr/keras-retinanet#324]
Currently the method for configuration is only those arguments that are exposed in `train.py`. I'm considering other methods of configuration, such as anchor scales / ratios, image sizes, IOU thresholds, training schedules, etc. `py-faster-rcnn` and `Detectron` seems to use a configuration file for this. I'm not completely convinced their method is the best way to handle this issue.

Ideally there would be an order of preference. Command line arguments have highest priority, then a configuration file, then default values. Although I'm not sure if exposing every configuration option through command line is desirable.. there are already many options available and it could become cluttered.

**Comment by maxcrous** [comment]
I don't have much in the way of good advice, but I'm very glad to hear that you're going to go through with configurable anchor scales/ratios. 

A support for configuration files would make handling different configurations for different projects easier, as users now have to rely on command line history or stored text files to look up used commands, which is, in essence, a kind of awkward configuration file. 

To use an order of preference seems like a good way of incorporating the freedom of configuration files whilst keeping the current intuitive command line interface and sticking to the same working defaults. 

Personally, I wouldn't include anchor scales/ratios, IOU thresholds, learning rates or any other "low level" settings in the command line interface, as it will be to the detriment of the plug-and-play, you've-set-all-relevant-parameters nature of the program.
I mean this in the sense that you won't find yourself saying "let's try these custom anchor scales" that often, and that users possibly shouldn't be exposed to such tinkering in the command line.

**Comment by nic25** [comment]
Hi - I think a viable solution could be to use argparse to store and pass all the arguments, and a config (json?) file to set the default values. 
If we load the config/defaults as a dictionary we can "set_default" to pass such arguments. First we can pass the "global" default, and then a "local" config. In this way we can set the precedence "_Command line arguments have highest priority, then a configuration file, then default values._".

To reduce the clutter we can "hide" such arguments, perhaps leaving an option to override such.

The main advantage is that argparse would be a "chokepoint" where all the settings have to go through. In this way is easy for the user to understand what settings they can change (and how).

**Comment by de-vri-es** [comment]
> I think the best way is to use a config.py file for it. Something like this:

Thank you for the suggestion. There are very good reasons to keep configuration and code separated though. The main reason is that it should be easy to use a different configuration file from the command line. Fiddling with the python import path is not a good way to support that in my opinion. A command line flag indicating the configuration file to load is much easier on the user.

Python also has some very easy methods for reading json/yaml/ini files into a dictionary, so I don't see the gain from using a config.py over one of those.

**Comment by hgaiser** [comment]
I would be in favour of subclassing `keras.models.Model` and override its `get_config` method. This is possible since keras 2.2.0. I tried it a little bit, but ran into some [issues](https://github.com/keras-team/keras/pull/10046). Storing it in the model has the added benefit of also being saved to the `.h5` file, so you don't need to couple your config file and model weights together, you just have one file with all the configs inside it.

If someone has time to try out the model subclassing, by all means go for it. I don't have much time for it. When I do, I'll check it out and I'll put my results here.

**Comment by de-vri-es** [comment]
That's not a solution for passing options to `train.py` as far as I can tell. I agree it is nice to be able to reconstruct model parameters from the `.h5` file, but it has little to do with the generator configuration (for example).

**Comment by hgaiser** [comment]
> That's not a solution for passing options to train.py as far as I can tell. I agree it is nice to be able to reconstruct model parameters from the .h5 file, but it has little to do with the generator configuration (for example).

Having the configuration in the model is one part of the solution, the other is exposing them in `train.py` somehow, I agree. I do think all config (including generator configuration) can and should be stored inside the model. The generator constructor should receive the generator-specific config from the model.

**Comment by de-vri-es** [comment]
To bo clear: I believe you mean only those generator options that relate to the model like the anchor configuration. That pretty much excludes everything that is currently configurable about generators (like their type and where they get their data from).

**Comment by hgaiser** [comment]
Yes, pretty much.

**Comment by AlliedToasters** [comment]
This is a tricky issue that's currently holding up my project. I had to halve the base_size value in anchors.generate_anchors() and I removed the .5 and 2 aspect ratios (since my objects, specifically impact craters, are circular in all cases, so square bounding boxes do the trick.) After successfully training the model, the inference model does not give sensible results; I suspect this has to do with the anchors that get "baked in" to the model when we convert, but I'm having trouble getting these values right. I tried modifying the values in AnchorParameters.default in the retinanet.py script before running convert_model.py, but this raises a TensorFlow error at runtime:

`---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-4-73ee04c18bae> in <module>()
     35 img = tile.subtiles[tileno]._produce_image()
     36 #img = rt_process(img)
---> 37 boxes, scores, labels = model.predict(np.expand_dims(img, axis=0))
     38 result, scores_ = prediction_to_craters(boxes, scores, labels)
     39 as_df = craters_to_df(result)

~/miniconda3/envs/dev/lib/python3.6/site-packages/keras/engine/training.py in predict(self, x, batch_size, verbose, steps)
   1170                                             batch_size=batch_size,
   1171                                             verbose=verbose,
-> 1172                                             steps=steps)
   1173 
   1174     def train_on_batch(self, x, y,

~/miniconda3/envs/dev/lib/python3.6/site-packages/keras/engine/training_arrays.py in predict_loop(model, f, ins, batch_size, verbose, steps)
    295                 ins_batch[i] = ins_batch[i].toarray()
    296 
--> 297             batch_outs = f(ins_batch)
    298             if not isinstance(batch_outs, list):
    299                 batch_outs = [batch_outs]

~/miniconda3/envs/dev/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2659                 return self._legacy_call(inputs)
   2660 
-> 2661             return self._call(inputs)
   2662         else:
   2663             if py_any(is_tensor(x) for x in inputs):

~/miniconda3/envs/dev/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
   2629                                 symbol_vals,
   2630                                 session)
-> 2631         fetched = self._callable_fn(*array_vals)
   2632         return fetched[:len(self.outputs)]
   2633 

~/miniconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/client/session.py in __call__(self, *args)
   1452         else:
   1453           return tf_session.TF_DeprecatedSessionRunCallable(
-> 1454               self._session._session, self._handle, args, status, None)
   1455 
   1456     def __del__(self):

~/miniconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: Incompatible shapes: [1,9441] vs. [1,3147]
	 [[Node: boxes/mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](boxes/add, boxes/sub)]]
	 [[Node: filtered_detections/map/while/PadV2_1/paddings/_1393 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2366_filtered_detections/map/while/PadV2_1/paddings", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/PadV2_2/constant_values/_1253)]]`

In any case, global anchor configurations that cover both train and test needs would be extremely useful.  Let me know if you have any advice for how I can hack this thing into submission in the meantime.

**Comment by hgaiser** [comment]
Randomly found this stackoverflow question:
https://stackoverflow.com/questions/51806852/cant-save-custom-subclassed-model?noredirect=1#comment90569852_51806852

Seems subclassed models can't be saved. How useful! /sarcasm

**Comment by hgaiser** [comment]
I'm closing this because of https://github.com/fizyr/keras-retinanet/pull/674
