### ISSUE TITLE
multi channel images

### ISSUE THREAD

**Issue by adarvit** [fizyr/keras-retinanet#361]
Hi, I am wondering if it is possible to use retinanet for 4 channels images. where is the best place to start for making modification of the code?

**Comment by jonla1** [comment]
Aside from converting your image, The easiest solution is to prepend a conv2D layer with 3 filters to get the right shape but you would have to train longer for the layer weights to adjust themselves properly.

**Comment by hgaiser** [comment]
I've never tried this, but thought about it. You could change the pretrained weights so that the expected number of channels for the first conv layer is 4. The new weights (for the fourth channel) would be initialised to all zeros. The idea is that the network will learn to incorporate that new channel.

The alternative of adding a new layer before the first or skipping the loading of those weights all together would basically destroy the foundation on which subsequent featured are based on. With the proposed method, if you run say an RGBD image through the network, it will still detect objects. It would have simply ignored the D channel. After training it might find the D channel useful and uses it.

**Comment by jonla1** [comment]
Incorporating your @hgaiser idea. Couldn't the weights of the prepended 3 filter Conv2D layer be intialized so that it is the identity function on the rgb image (all zero weights except for depth channel). I think this way is much less work to implement.

**Comment by hgaiser** [comment]
Good point, that could work. I'm not sure about the effect of reducing the number of channels to 3 right away, compared to the method I proposed though. Would be an interesting test.

**Comment by hgaiser** [comment]
I'll close this issue, it appears to have been answered.
