### ISSUE TITLE
Generating Anchor Boxes question implementation

### ISSUE THREAD

**Issue by Shiro-LK** [fizyr/keras-retinanet#451]
Hello,

I am trying to understand the code regarding the generation of anchor boxes. From what I understood, (utils/anchor.py) we compute the different size of the feature map (with the stride) and associated the anchor for each of these feature maps. 

1) I do not fully understand  the function anchors_for_shape. In fact, the function generator_anchor seems to generate the size of the different anchors, but the function shift seems to apply the anchors on the feature map of the image but I am not sure because I do not understand exactly what the function is doing. Is it possible to have some explanation about it ?

2)  I do not understand when we associate the label of each anchor generated. If I understand well, our anchor label has shape MxNxAx4 (regarding the regression) with M and N the size of a feature map and MxNxKxA (with K number of classes, K number of anchor scale/ratio) for the recognition pass. But I do not find where we do that.

Thanks in advance for the help !

**Comment by hgaiser** [comment]
> I do not fully understand the function anchors_for_shape. In fact, the function generator_anchor seems to generate the size of the different anchors, but the function shift seems to apply the anchors on the feature map of the image but I am not sure because I do not understand exactly what the function is doing. Is it possible to have some explanation about it ?

The function `generate_anchors` generates (by default) 9 anchors for a specific pyramid level, these are what is called the "base" anchors. The `shift` function shifts (or slides) these anchors over the feature map so that each feature pixel has those 9 anchors. The `anchors_for_shape` function uses these two functions to generate anchors for each pyramid level.

> I do not understand when we associate the label of each anchor generated. If I understand well, our anchor label has shape MxNxAx4 (regarding the regression) with M and N the size of a feature map and MxNxKxA (with K number of classes, K number of anchor scale/ratio) for the recognition pass. But I do not find where we do that.

The regression map computed is actually of shape `(M, N, K * A)` since that makes a couple of things easier. The assigning of labels to anchors happens [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/anchors.py#L44). For each anchor the overlap with each annotation is computed. Using the maximum overlap for each anchor, the corresponding annotation (and its label) is selected in that line.
