### ISSUE TITLE
Question about the model's code

### ISSUE THREAD

**Issue by Shiro-LK** [fizyr/keras-retinanet#496]
Hello,

I am trying to understand the training code, but I am a little lost. In fact, I do not find the function "backbone" used in train.py line 378 `models.backbone(args.backbone)` . I found a folder called models, but the files are retinanet, resnet etc. So where does models.backbone come from ?

My second question is about the feature map used for the pyramidal features in retinanet.py. `C3, C4, C5 = backbone_layers` if I understand well, backbone_layers is the resnet network (by default) called in the function resnet.py but how do we get theses features maps ? Have I missing a function or something ?  I thought backbone_layers was the model without the last layers of the originial resnet model.

**Comment by hgaiser** [comment]
For your first question, I think looking at [this](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/__init__.py#L39) code will clarify some things.

For your second question, yeah, C3-5 are the feature maps of (for instance) ResNet. In keras-resnet the outputs are the layers at the different stages, which are passed to backbone_layers [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/resnet.py#L87).

Since this is not an issue with the code, but a discussion, I'm going to close it. For further discussions, please join the keras-retinanet slack channel.
