### ISSUE TITLE
Prediction on batches

### ISSUE THREAD

**Issue by raghavgurbaxani** [fizyr/keras-retinanet#643]
Hi 

Could you mention how to do predictions on batch size >1.

**Comment by twinanda** [comment]
Anybody has any ideas on how to do this?

**Comment by hgaiser** [comment]
You'd need to make a numpy array which holds both images. If they are not of equal size, then you need to pad with zeros so that they are equal in size. You can check [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/generator.py#L225-L233) for an example, which is how it is done for training.

Since this is not an issue with the code, I'll close it. Further discussions can be held on the Slack channel.
