### ISSUE TITLE
Target issue

### ISSUE THREAD

**Issue by Jaekyumkim** [fizyr/keras-retinanet#659]
Hi I trained your retinanet code and it worked well.

But i have one question.

You divide the targets by std([0.2,0.2,0.2,0.2]). 

Why did you divide this? Is the original retinanet did like this?

**Comment by hgaiser** [comment]
The original implementation is a bit unclear about how they handle it, but it is assumed it is similar or identical to FasterRCNN. There they used the stddev as calculated from COCO. We have since deviated a little bit of how the regression is applied to the anchors, since it gave better results on COCO, but the idea is the same. It is the stddev of COCO.

In other words, if you use keras-retinanet to compute the regression values for COCO, you would see an stddev of approximately 0.2 for all values.
