### ISSUE TITLE
Test example runs too slow

### ISSUE THREAD

**Issue by yijingru** [fizyr/keras-retinanet#660]
I download the weights from the release, and run the test example, it takes 234.39567971229553s on K40, is there any problem? Also, do you have  pretrained weights for resnet101 backbone?

**Comment by de-vri-es** [comment]
It is possible that the tensorflow you installed is not compiled to use cuda or cudnn, in which case the K40 remains unused. If that is the case then it's an issue with your environment rather than `keras-retinanet`.

Can you verify wether or not your K40 is being used by tensorflow at all?

As for pretrained weights for resnet101, I believe we do not have any. If you wish to contribute them, that would be great.

**Comment by hgaiser** [comment]
@yijingru did you find more time to look at this ?

**Comment by yijingru** [comment]
@de-vri-es @hgaiser I did use K40. But finally I found only the first image took a long time. I think it may be some pytorch loading problem?

**Comment by hgaiser** [comment]
Yeah the first run is always slower. In my experience with Titan X Pascal and 1080ti, it is more in the order of 2s for the first run and 0.08 when the GPU is "warmed up".

Should we consider the issue resolved?

**Comment by yijingru** [comment]
@hgaiser  Sure. Thanks a lot for the help.
