### ISSUE TITLE
No Usage possible (Tensorflow 1.5)

### ISSUE THREAD

**Issue by TimoK93** [fizyr/keras-retinanet#689]
Hi Folks and thanks for your awesome package!

I trained a net and tried to test it on different boards and machines to get an overview about the performance. In other words: I'm creating a benchmark image based on a net trained with your repository.

I trained the net on my PC with Nvidia 1050ti (latest tensorflow)-> worked well.
I processed images with the trained net on different plattforms -> worked well.

My problem:
Now I want to test this plattform: https://up-shop.org/up-boards/106-up-squared-pentium-quad-core-8gb-memory128gb-emmc.html. I think it's a nice system but unfortunately it dont supports tensorflow upper 1.5... So i installed tensorflow 1.5 (prebuilt) and keras. I tried to use some keras scripts -> and they worked. If i try to use the .predict_batch() method from your package, the execution freezes and nothing happens. 
A notice at this point: Tensorflow 1.5 was installed prebuilt and so it doesnt support some instructions. It raises this warning: 
`The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.`

My question: Do you have some experience with your package and the usage of Tensorflow 1.5 and are some "special" instructions necessary for your package?

It would be really great if you would have some experience or a tip!
Thanks in advance,
Timo Kaiser

**Comment by hgaiser** [comment]
Regarding the warning, I have seen that more often and is not necessarily an issue.

I haven't used tf 1.5 but I do know we're using some functions that have changed since then. So it could very well be that tf 1.5 is incompatible with our code. The reason those scripts work is because they likely don't use those functions. You can always compile a later version of tf (I would say 1.8 and up) on your board (or perhaps cross compile it to save time ;) ).

**Comment by TimoK93** [comment]
Thanks for your reply!
I will try it the next time and report.

**Comment by TimoK93** [comment]
I built tensorflow 1.10 by source -> Framework is working!
Thanks for help.

**Comment by hgaiser** [comment]
Awesome, thanks for the feedback :)
