### ISSUE TITLE
I got an error, when I trained on my own csv datasets, loss decreased as normal, but when I test on one image, model.predict_on_batch() function returns all -1 and detect nothing. 

### ISSUE THREAD

**Issue by Bigwode** [fizyr/keras-retinanet#736]
Epoch 50/50
2000/2000 [==============================] - 332s 166ms/step - loss: 0.2221 - regression_loss: 0.1693 - classification_loss: 0.0527 

rt. I retrained the model many times, it gives me the same error. I checked my dataset' label fold and can't find error.HELP PLEASE!

**Comment by vithmel** [comment]
I had a similar problem. In my case, the reason was that the bounding box was too close to the target.
All my data has been generated. The bounding box indent from the target was only one pixel. When I increased the indent to five pixels and trained model again, everything began to work.
![1112223333](https://user-images.githubusercontent.com/15888026/47016542-a75cbc80-d158-11e8-9cb1-8e4109efd30d.png)

**Comment by hgaiser** [comment]
Wow did you really just spam all these messages?

Your loss values seem fine, it's probably how you preprocess your image where it is going wrong.

Closing this as it is not an issue with the code.

**Comment by Bigwode** [comment]
@hgaiser I just follow the ReadMe and run the csv command but I got this error
