### ISSUE TITLE
How to convert a inference model to a standard keras model?

### ISSUE THREAD

**Issue by a6225301** [fizyr/keras-retinanet#769]
Hi, I have trained a model and converted it to a inference model to predict the image successfully. However, I wonder if it possible to convert the model to a keras standard model just by 'load_model' function and I want to use it by keras.js to reload the model. So is there any way to solve that ?

**Comment by hgaiser** [comment]
Check what our load model function does, it basically just wraps keras' load model and sets the custom objects. Because of these custom objects, I don't think you can simply load it in keras.js, you might need to port some layers so that the model can be loaded.

Closing this as it is not an issue with the code.
