### ISSUE TITLE
Anchor parameter

### ISSUE THREAD

**Issue by himachalbanik40** [fizyr/keras-retinanet#780]
[anchor_parameters]
sizes   = 32 64 128 256 512
strides = 8 16 32 64 128
ratios  = 0.5 1 2 3
scales  = 1 1.2 1.6

From the example config file what does scales and ratios mean here? Please if anyone can explain their significance.
Thank you.

**Comment by himachalbanik40** [comment]
where can i find the output of each FPN?

**Comment by hgaiser** [comment]
Let's discuss further on Slack.

**Comment by renmengyuan** [comment]
In the config.ini, the ratio means anchor-width:height or height:width?

**Comment by benihime91** [comment]
Hello. I am getting quite a headache regarding this whole anchor box generation thing. I asked this question here because it seems that someone at least replied to this thread:
My questions are:
1. What is `strides` in the config file ?
```
[anchor_parameters]
sizes = 32 64 128 256 512
strides = 8 16 32 64 128
ratios = 0.5 1 2 3
scales = 1 1.2 1.6
```
2. I was looking around different implementations of anchor generation . Looking at the `source-code` of `Detectron2` `AnchorGenerator` I found that Detectron 2 in not using the `scales` parameter . https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/anchor_generator.py

I would be really grateful if some provides an explanation.

Thanks

**Comment by SarBH** [comment]
Hi @benihime91 wondering if you got your answer? i feel the headache too..
