### ISSUE TITLE
Ground truth bounding boxes with IOU < 0.5

### ISSUE THREAD

**Issue by tarrencev** [fizyr/keras-retinanet#81]
This is more of a general question about retinanet and dense detection:
In the case where a ground truth bounding box doesn't have an IOU score of >= 0.5 with any of the anchor proposals (small items), is it not added to the set of ground truth targets? And if this is the case, does that mean that if the net correctly predicts the object, it is penalized?

**Comment by hgaiser** [comment]
It's better to keep these discussion on the Slack channel (#keras-retinanet) so that these issues can be used for technical issues.

That being said, your assumptions are correct. If there is no anchor which overlaps significantly with a ground truth object, the network will try to label each anchor as "background".

Lets have further discussions on the Slack channel, closing this issue.
