### ISSUE TITLE
Question about load models

### ISSUE THREAD

**Issue by dasing** [fizyr/keras-retinanet#817]
Hello, 
I found that in train.py, Line442 (https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L442)
model.load_models will only load the weight of FPN, it seems like it won't load the weight of prediction_models for regression and prediction? Why and why not?

Thank you!

**Comment by hgaiser** [comment]
It probably won't load the weights for the classification submodel, but it should load it for the regression submodel (assuming your number of classes is different in the weights you're loading). The reason is that the loading of weights is skipped if the size of the weights is different in the weights and the model where you're trying to load the weights into, because of the different number of classes. The regression submodel does not depend on the number, so it can be loaded.
