### ISSUE TITLE
how can I save pictures of augmentation?

### ISSUE THREAD

**Issue by nosa999** [fizyr/keras-retinanet#876]
I use data augmentation as bellow picture, but the loss_classification and loss_validation a few increase after it, and my question is that: does the data augmentation really work or not? and how can save the pictures that produce with data augmentation?
![image](https://user-images.githubusercontent.com/40929193/51400345-66ac7f00-1b5d-11e9-8da2-277f2ab636cc.png)

and in the below are some results:
with data augmentation:
![image](https://user-images.githubusercontent.com/40929193/51400470-b9863680-1b5d-11e9-92b7-8a22cc85e814.png)

without data augmentation:
![image](https://user-images.githubusercontent.com/40929193/51400522-dae72280-1b5d-11e9-94fe-045b08cd8c65.png)

**Comment by Ezereal** [comment]
I think data augment is more powerful when you data is not enough and if you want to save the pictures after data augmentation, you can write the save code in preprocessing/generator.py.

**Comment by martinzlocha** [comment]
It looks like you are using notepad++ which by default uses tabs, you should however use normal spaces instead.

**Comment by hgaiser** [comment]
I think the question has been answered. Regarding your loss values, both cases seem fine and expected. It will take longer for the network with data augmentation to get to the same loss value, because it is using more difficult data. In the end the result is likely better with data augmentation, but give it a shot and compare.
