### ISSUE TITLE
Train own dataset in PASCAL format

### ISSUE THREAD

**Issue by kevinkit** [fizyr/keras-retinanet#887]
I read the FAQ "How do I train my own dataset", where it states that one should use the .csv files, however I have my .xml files with my own dataset in PASCAL format. 
I wonder if it is possible to avoid transfering the XML files in CSV files, and directly use the PASCAL format. 

When using the `train.py` file with pascal command, I will get the error:

> 
>  FileNotFoundError: [Errno 2] No such file or directory: ' ..\\labels\\ImageSets\\Main\\trainval.txt'

Which is not provided, of course, so I wonder if there is like a special folder structure that needs to be maintained, which would be easier than handling the xml files to the csv files

**Comment by hgaiser** [comment]
If you wish to use the PASCAL format with your own classes you'll need to do some modifications. Your issue comes from the expectations that the set files have a certain name (which they do for PASCAL VOC). Look at the PASCAL generator and you'll quickly see which parts require changing. You should be able to use the PASCAL generator without actually modifying the generator itself. Only the arguments to the PASCAL generator constructor and your dataset format should need modifications.

Closing this as it is not an issue with the code base. Feel free to discuss this further on the Slack channel.
