### ISSUE TITLE
How about batch_size=64 or 128 when training coco2017 dataset ? 

### ISSUE THREAD

**Issue by DehuaTang** [fizyr/keras-retinanet#94]
Thank you for sharing your work !
I noticed that the batch_size=1 in your program. Have you tried  batch_size=64 or 128  when training coco2017 dataset ?...Could the mAP raise to 34% as mentioned in the paper ?  
I don't have so many GPUs .  So I hope to get some advice from you . 
Thank you !

**Comment by hgaiser** [comment]
Just recently we added the ability to train with larger batch sizes. Theoretically it should be working, but we have yet to test it completely. That being said, I don't know if training with larger batch sizes will increase mAP (though I have my doubts). It is something that we're currently looking into.

I will close this issue since it's not really an issue. If you like to discuss more or have further questions, feel free to join the Slack channel (#keras-retinanet).
