### ISSUE TITLE
csv training questions

### ISSUE THREAD

**Issue by HuangBo-Terraloupe** [fizyr/keras-retinanet#99]
I have few questions about the csv format we should use:
1, if there are multiple bounding box within one image, we should save the csv like:
    A: img1, x1, y1, x2, y2, cow, x1, y1, x2, y2, cat       or
    B:  img1, x1, y1, x2, y2, cow, 
          img1, x1, y1, x2, y2, cat

My question is should we put it in the same line or create a new line for it?

**Comment by yhenon** [comment]
1 - it should be like B, so:
img1, x1, y1, x2, y2, cow
img1, x1, y1, x2, y2, cat

2 - no need to include bg, it is implicit. Classes start at 0.

I'll go ahead and update the readme, anything else unclear?

On Nov 23, 2017 8:17 AM, "HuangBo-Terraloupe" <notifications@github.com>
wrote:

I have few questions about the csv format we should use:
1, if there are multiple bounding box within one image, we should save the
csv like:
A: img1, x1, y1, x2, y2, cow, x1, y1, x2, y2, cat or
B: img1, x1, y1, x2, y2, cow,
img1, x1, y1, x2, y2, cat

My question is should we put it in the same line or create a new line for
it?

2, question about the csv for class_mapping:
Is this class mapping should like the dict {cat:0, dog:1, cow:2}?
should we include 'bg', background?
the number start from 0 or 1?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fizyr/keras-retinanet/issues/99>, or mute the thread

**Comment by HuangBo-Terraloupe** [comment]
thanks, I have succesfully setup the training. thanks for your work! 

Maybe we need few more things:
1, validation acc and training acc
2, evaluation code for classification and detection.

For you old repository, faster rcnn keras, I write my own script to do that, maybe we can talk about it.

**Comment by hgaiser** [comment]
I agree, we really need an evaluation script. I've already sort-of begun to implement an evaluation procedure, but haven't finished it yet.
