### ISSUE TITLE
Impact of input image size on RetinaNet

### ISSUE THREAD

**Issue by amardeepjaiman** [fizyr/keras-retinanet#992]
whats the impact of image size on RetinaNet trainning and inferencing.

as my image size if 512x512, and By default Retinanet resize the training images to 800x1333 , does it necessary to do this upscaling for better results ? or this resizing is only required for large resolution images?

Is it necessary to have same size of images for inferencing which were used for training ? like if i had 512x512 images size for training then can i input any other size image directly for inferencing in RetinaNet ?

**Comment by ManuelVazquezEnriquez** [comment]
By default:
 --image-min-side = 800
 --image-max-side = 1333 

If you check the resize function:

	min_side: The image's min side will be equal to min_side after resizing.
	max_side: If after resizing the image's max side is above max_side, resize until the max side is equal to max_side.

So if you have a square image of 512x512 and you use the default values it will be resized to 800x800
In any case, according to your image size use --image-min-side = 512 I think it would not make sense to use the default values.

**Comment by amardeepjaiman** [comment]
Thanks @ManuelVazquezEnriquez for your input. Could you please answer the 2nd questions also  ?

is it mandatory to have the same size images for inferencing on which retinanet is trained. For eg. If i have used 512x512 size for training then should i have same dimension while inferencing ? or can i do the inferencing on large resolution images directly?

**Comment by scstu** [comment]
**That's a really interesting Question!!** 
I have the same thing, I trained may detector on the default configuration. I evaluated the system with different image size. but I got the same processing time (~0.1 per image). Now, I am thinking whether it's possible to train the detector with **VGA** format (640 pixels wide and 480 pixels high) so I can get less processing time during inference. 

answering your Question: No, No need to rescale your image, because RetinaNet resize the image to get the appropriate size by default.

**Comment by hgaiser** [comment]
In general I would advise to keep your settings the same during inference and training. I'm pretty sure that if you run differently sized images through the network (compared to the sizes while training), you will see degraded performance).
